import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ThemeProvider, {
  ThemeSwitcher,
  ThemeBackground,
  useTheme,
} from "../../components/ThemeProvider";
import KittenMascot from "../../components/KittenMascot";
import WelcomeMessage from "../../components/WelcomeMessage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
      >
        <ThemeProvider>
          <ThemeSwitcher />
          <ThemeBackground />
          <div className="flex flex-col items-center pt-4 pb-0">
            <KittenMascot size={140} />
            <WelcomeMessage />
          </div>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
